before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
bundler_args: --without development
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
